version: '3.4'

services:
  collector:
    image: stock_data_collector
    container_name: stock_data_collector
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../..:/home/appuser/host
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["sleep", "infinity"]
    ports:
      - "5000:5000"
    environment:
      - DISPLAY=:1
      - QT_DEBUG_PLUGINS=1
      - TZ=Australia/Brisbane
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=stock_data
    privileged: true
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
    depends_on:
      - postgres


  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: stock_data
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


secrets:
  db_password:
    external: true