version: '3.4'

services:
  collector:
    image: stock_data_collector
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/appuser
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["bash", "stock_data_collector_init.sh"]
    ports:
      - "5001:5001"
    environment:
      - DISPLAY=:1
      - QT_DEBUG_PLUGINS=1
      # - TZ=Australia/Brisbane
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=appuser
      - PGPASSFILE=/run/secrets/pg_pass_file
      - PGDATABASE=stock_data
    privileged: true
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
    depends_on:
      - postgres
    deploy:
      replicas: 1
    networks:
      - overlay_network
    secrets:
      - source: pg_pass_file
        target: pg_pass_file
        mode: 0400
        uid: '1000'  # appuser
        gid: '1000'  #appuser

  postgres:
    image: postgres
    restart: always
    environment:
      PGUSER: appuser
      PGPASSWORD_FILE: /run/secrets/pg_pass_file
      PGDATABASE: stock_data
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
    networks:
      - overlay_network
    secrets:
      - pg_pass_file

secrets:
  pg_pass_file:
    # generated from docker secret command
    # echo "password" | docker secret create pg_pass_file -
    external: true

networks:
  overlay_network:
    driver: overlay