version: '3'

tasks:
  load_nasdaq_tickers:
    desc: Load tickers that are downloaded from https://www.nasdaq.com/market-activity/stocks/screener 
    cmds:
      - go run tasks/task_runner.go load_nasdaq_tickers data/nasdaq_screener_1742045443432.csv 20
  
  download_sa_page_for_symbol:
    desc: Download SA pages for one symbol
    cmds:
      - go run tasks/task_runner.go download_sa_page_for_symbol data/proxies1.txt AAPL

  download_sa_pages:
    desc: Download SA pages
    cmds:
      - go run tasks/task_runner.go download_sa_pages data/proxies1.txt 50

  scrape_sa_pages:
    desc: Extract information from SA pages
    cmds:
      - go run tasks/task_runner.go scrape_sa_pages data/testdata 1

  clear_db:
    desc: drop database schema
    cmds:
      - go run tasks/task_runner.go clear_db


  clear_cache:
    desc: clear cache
    cmds:
      - go run tasks/task_runner.go clear_cache

  reset:
    desc: clear database and cache
    depends_on:
      - clear_db
      - clear_cache
      