#FROM python:3.10-slim-bookworm
FROM ubuntu/python:3.12-24.04_stable

WORKDIR /app

RUN pip install "openbb[all]"
RUN pip install openbb-platform-api

EXPOSE 6900

ENTRYPOINT ["openbb-api", "--host", "0.0.0.0", "--port", "6900"]
