// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: scrape.proto

package HtmlScraper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HtmlScraper_ProcessPage_FullMethodName = "/HtmlScraper.HtmlScraper/ProcessPage"
)

// HtmlScraperClient is the client API for HtmlScraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务定义
type HtmlScraperClient interface {
	// 处理 HTML 文本并返回 JSON 格式的数据
	ProcessPage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type htmlScraperClient struct {
	cc grpc.ClientConnInterface
}

func NewHtmlScraperClient(cc grpc.ClientConnInterface) HtmlScraperClient {
	return &htmlScraperClient{cc}
}

func (c *htmlScraperClient) ProcessPage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, HtmlScraper_ProcessPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HtmlScraperServer is the server API for HtmlScraper service.
// All implementations must embed UnimplementedHtmlScraperServer
// for forward compatibility.
//
// 服务定义
type HtmlScraperServer interface {
	// 处理 HTML 文本并返回 JSON 格式的数据
	ProcessPage(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedHtmlScraperServer()
}

// UnimplementedHtmlScraperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHtmlScraperServer struct{}

func (UnimplementedHtmlScraperServer) ProcessPage(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPage not implemented")
}
func (UnimplementedHtmlScraperServer) mustEmbedUnimplementedHtmlScraperServer() {}
func (UnimplementedHtmlScraperServer) testEmbeddedByValue()                     {}

// UnsafeHtmlScraperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HtmlScraperServer will
// result in compilation errors.
type UnsafeHtmlScraperServer interface {
	mustEmbedUnimplementedHtmlScraperServer()
}

func RegisterHtmlScraperServer(s grpc.ServiceRegistrar, srv HtmlScraperServer) {
	// If the following call pancis, it indicates UnimplementedHtmlScraperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HtmlScraper_ServiceDesc, srv)
}

func _HtmlScraper_ProcessPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HtmlScraperServer).ProcessPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HtmlScraper_ProcessPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HtmlScraperServer).ProcessPage(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// HtmlScraper_ServiceDesc is the grpc.ServiceDesc for HtmlScraper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HtmlScraper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HtmlScraper.HtmlScraper",
	HandlerType: (*HtmlScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPage",
			Handler:    _HtmlScraper_ProcessPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scrape.proto",
}
